eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    hostname: clientName
    prefer-ip-address: true
    instance-id: 192.168.2.174:client
spring:
  application:
    name: client